# Generated by Django 5.2.17 on 2026-09-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budget_unique_budget_per_user_category_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='budget',
            name='last_alert_level',
            field=models.CharField(blank=True, choices=[('warning', '80%'), ('reached', '100%')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='last_alert_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
